version: '3.4'

services:
  producerservice:
    image: ${DOCKER_REGISTRY-}producerservice
    build:
      context: .
      dockerfile: ProducerService/Dockerfile

  consumerservice:
    image: ${DOCKER_REGISTRY-}consumerservice
    build:
      context: .
      dockerfile: ConsumerService/Dockerfile

  postgresDb:
    image: postgres

  sqlserverDb:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: "rabbitmq:3-management"

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka



